### ISSUE TITLE
Why not Implment Windows.Web.Syndication.SyndicationFeed entirely?

### ISSUE THREAD

**Issue by skyhoshi** [Microsoft/Windows-appsample-rssreader#6]
Is there a reason you didn't bind your feed items (ArticleViewModel) directly to the feed SyndicationItems? [ListView Bound to the feeds list items]

I'm trying to understand why you created a custom view model, could you not bind directly to the Feed items. 

I see that SyndicationFeed and SyndicationItems are sealed classes. but I'm missing the connection between why they weren't implemented directly in the view model. (Why was a custom model used?) 

Thanks

**Comment by KarlErickson** [comment]
Hi skyhoshi,

Good question! The main reason to use a view model instead of binding directly to the underlying model is to extend or reshape it. In the case of ArticleViewModel, the IsStarred property is the extension. 

An alternative design would be to have ArticleViewModel contain an IsStarred property and a SyndicationItem property that exposes the underlying model object directly for one-time bindings. That way you can use the existing type while adding a VM layer just to add the UI-only property. This is a reasonable design, but you lose the ability to reshape or clean up the underlying data if you need to. With ArticleViewModel, there is a bit of clean-up that takes place in the FeedDataSource.TryGetFeedAsync method, when the ArticleViewModel properties are set. 

Finally, ArticleViewModel exposes only a subset of properties available on SyndicationItem. These are the only properties that FeedDataSource will try to make sure are always available to the UI designer for binding purposes. Many SyndicationItem properties are inconsistently used by different feed providers, so it was useful to us to let the UI designer know that only the VM properties should be used to create the UI. 

I hope this helps!

-Karl
